### ISSUE TITLE
Project Obstacles Rough Draft

### ISSUE THREAD

**Issue by cmccachern** [cmccachern/asteroid_detection#4]
Write a rough draft of the potential obstacles that we might encounter.  This should be in the overview section of the [project proposal on Google Docs](https://docs.google.com/document/d/1oUi6EOHiIXMLRXasYGh0ok1eILKHiFhQeFdF1D7R7Ko/edit?usp=sharing).

**Comment by cmccachern** [comment]
Finish this by Monday 9/16 so that we can finish the final draft in time.

**Comment by agruszyn** [comment]
Rough draft completed. Ready for review and Final draft
